### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#18]

**Comment by fionafyzeng** [comment]
- Carrie's Original [Google Slides](https://docs.google.com/presentation/d/1xJSEDUYIWcXeDDzByzKtGDmzbQi3OKd7w5pEsHNdLJI/edit?usp=sharing) (Slides 1-5)
- Fiona Zeng's [Figma Draft](https://www.figma.com/file/JjYn4tAdyqqnXGCC8OtWIq/Oppia-files-owned-by-Fiona-Zeng?node-id=0%3A1) (See page "Personas")

**Comment by fionafyzeng** [comment]
FZ created profile cards on Figma, and then imported those graphics into Carrie's Google Slides. FZ created Slides 6-9 (4 slides) that includes revisions of clarity in wording and format.

FZ's 4 added slides of Personas are:

1. Educator Group Persona: Elementary school teacher
2. Learner Group Persona*: New learner at home
3. Contributor Group Persona: Volunteer Contributor
4. Donor Persona*: Prospective NGO

*FZ combined the following original personas because personas work when you cater with an immersive quality experience for the persona requires the most support.

- Learner Group Persona combined the needs/motivations/frustrations/goals of Existing Learners In School; New Learners In School; Existing Learners at Home; New Learners at Home; Parent.
- Donor Persona combined the needs/motivations/frustrations/goals of Unsolicited Donors; Solicited Donors; Prospective NGO Partners.

**Comment by seanlip** [comment]
Julia is working on this and it's tracked separately as a broader collaboration with the UXR team, so I'm going to close this issue.
