### ISSUE TITLE
Learner Dashboard Redesign

### ISSUE THREAD

**Issue by ghost** [oppia/design-team#45]
[Primer](https://docs.google.com/document/u/1/d/1PIs9QaEF_Itbj_H8lLWe-NsP18QSNY0f_JLsZW2e_PQ/edit)
Rebekah (UXW) has already started some of the initial work of laying out the IA but we'd love a designer to partner with once we have a high level structure for what we want the new IA to be.

**Comment by dchen97** [comment]
[Primer doc](https://docs.google.com/document/d/1PIs9QaEF_Itbj_H8lLWe-NsP18QSNY0f_JLsZW2e_PQ/edit#heading=h.sog8gbegpsj9) now includes the finalized IA proposal and links to the Figjam of what @rebekahnt30 worked on!

**Comment by ghost** [comment]
@juliafalarini Are you working on the learner dashboard redesign? If so, could you add the next milestone and next milestone due dates to GitHub as you move through the project?

**Comment by juliafalarini** [comment]
> @juliafalarini Are you working on the learner dashboard redesign? If so, could you add the next milestone and next milestone due dates to GitHub as you move through the project?

Hi @findimue :) I'll have a meeting with @dchen97 to discuss about this project this week, but I haven't started working on it yet.

**Comment by juliafalarini** [comment]
**Done**

- Wireframes/Lo-fi prototype for Learner Dashboard (has been reviewed by Diana (PM) and Rebekah (UXW)).
- [Research Plan](https://docs.google.com/document/d/1ixee6_9Dsf89Hob5N3cBI25YY7iw7ORxS-HLGKVgExU/edit?usp=sharing) 

**In progress**

- Conducting usability tests with users


**Next steps (by March 22nd):**

- Consolidate results from tests and finish necessary adjustments in the low-fi flows/wireframes; 
- Update the research plan so more feedback can come in

**Comment by juliafalarini** [comment]
[Submit Report Web Improvements (Responses) Spreadsheet](https://docs.google.com/spreadsheets/d/1BNkynOkA4H_uEIFwf9-6qFJYhcxfFU8cfuXZgI3UetQ/edit?usp=sharing)

**Comment by juliafalarini** [comment]
Consolidating the tests results [here](https://docs.google.com/spreadsheets/d/18Hyoy2yWgAsgAKVCt1lTVd8DajGu1vM4YIAdqme_tLQ/edit?usp=sharing). @dchen97 has reviewed it. Waiting for @sarahking22 to find a time to meet and discuss it.

**Comment by juliafalarini** [comment]
After consolidating results, I have updated the mocks and created a second version of the [Research Plan](https://docs.google.com/document/d/1l5C-FmPeuzMwH0aBF2pal0lqyqaleBn6WxkLuZ9DOOE/edit?usp=sharing) and [Prototype](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?node-id=3521-27960), to test some improvements. One Outreachy contributor has already submitted a [report](https://docs.google.com/spreadsheets/d/1swIL-orNlcE-R6bqqDyb95vaN2zXZw56Dgzg5TrKaB4/edit?usp=sharing).

**Comment by juliafalarini** [comment]
- I've done new updates to the [Learner Dashboard](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?node-id=3248-27299) after some feedback I had from Sean and Diana. 
- One issue I've been facing is to create a Lesson Card that can be used for both curated lessons and community lessons. In the prototype you can see the latest version proposed, and I'd like to know your thoughts.
- I've proposed a more detailed view of the progress of the goals. The idea is that the user can resume/start the next lesson of the goal without expanding the dropdown, but if they want to see in detail, they can see which chapters they have already done, and which chapters are left.
- I've proposed a more detailed view of the Skills section as well. Previously I was only considering Place Values and Multiplication, since we only have practice questions and revision cards for these two topics. However, we might have more topics in the future, so I've updated the prototype for future scenarios.

Next steps:
- Now I'm working on the [Research Plan for the Learner Dashboard](https://docs.google.com/document/d/1jSmMoFeJoksvXt3nJCo9AhFthniceWKLx_1BhaAKkI4/edit?usp=sharing). I'm planning to test it with users who have participated in the [Web Onboarding Research](https://docs.google.com/document/d/1ixee6_9Dsf89Hob5N3cBI25YY7iw7ORxS-HLGKVgExU/edit?usp=share_link), so we can simulate a user that would have already created an account and played a lesson, and now is exploring more of the learner Dashboard.
- The tests will be conducted this weekend, so if I could get a feedback ASAP, that would be very helpful. Thanks!

**Comment by juliafalarini** [comment]
I've finished updating the mocks for the Learner Dashboard, you can check it [here](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?node-id=3248-27299). My next steps are to create a fully-implementable clickable prototype + notes for handoff by April 28th.

**Comment by juliafalarini** [comment]
The designs for all screen sizes for the [Learner Dashboard ](https://www.figma.com/file/YWe7SqfUVjxlJLKTUn0UZa/Project-2?node-id=3248-27299)are finished, and I've also created a "Notes/Instructions" section on Figma to add notes for development. I haven't had any feedback these last few days, so I hope everything looks fine. @dchen97  If any of you have any questions, please let me know!

**Comment by seanlip** [comment]
This issue doesn't seem to have been closed properly -- I can't find a corresponding issue on https://github.com/oppia/oppia/issues. @dchen97 did you update an old issue or something like that? (I can't see a reference to that in previous comments on this thread.)

Moving back to "Handed off to PM".

**Comment by dchen97** [comment]
Filed [issue](https://github.com/oppia/oppia/issues/18384)
